name: Extract Metal Toolchain DMG

on:
  workflow_dispatch:

jobs:
  extract:
    runs-on: macos-26
    steps:
      - name: Use ditto to create cpio with xattrs preserved
        run: |
          set -e
          cd /System/Library/AssetsV2
          sudo ditto --rsrc --extattr -c com_apple_MobileAsset_MetalToolchain $GITHUB_WORKSPACE/metal-toolchain.cpio
          ls -la $GITHUB_WORKSPACE/metal-toolchain.cpio
          sudo chown $(whoami) $GITHUB_WORKSPACE/metal-toolchain.cpio
          gzip $GITHUB_WORKSPACE/metal-toolchain.cpio
          ls -la $GITHUB_WORKSPACE/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MetalToolchain-ditto
          path: metal-toolchain.cpio.gz
          retention-days: 1
